# I'm feeling a little Bowie

## Introdução

Digamos que eu esteja me sentindo de uma maneira muito específica, e eu queira ouvir uma música que consoe meu estado de espírito. Para isso, podemos usar técnicas de Processamento de Linguagem Natural (PLN) para analisar o sentimento de uma frase ou texto e, em seguida, recomendar uma música que corresponda a esse sentimento.

Lógicamente, o universo musical é vasto e diverso, há todavia um artista com tamanho alcance e talento que faz com que todos os outros sejam irrelevantes: David Bowie.

Dessa forma, podemos criar um chatbot que, dada uma descrição do seu estado de espírito, responda a música ideal para enriquecer o seu ser.

## Dados

### Obtenção

Em primeiro lugar é necessário obter todas as letras das músicas de David Bowie. Para tanto, foi utilizado o site [Bowie Wonderworld](https://www.bowiewonderworld.com/songs/dblyrics.htm), que contém todas as letras das músicas do artista. A partir desse site, é possível realizar uma cópia bruta (é necessário desativar os scripts do site para tanto) de todas as letras para um arquivo de texto.

### Transformação e anotação

Primeiramente é necessário transformar o arquivo bruto em um arquivo estruturado, de forma que cada música seja representada por uma linha, contendo o título da música, a letra e o sentimento.

Devido ao altíssimo volume de músicas, a anotação manual de sentimentos para cada música seria inviável.
Por tanto, conclui-se que a a utilização de assistência de IA seria a solução mais apropriada.

A transformação e anotação ocorreram por tanto através do Copilot,
 utilizado o modelo GPT-5.6 Sol, janela de contexto de e raciocínio padrão com o seguinte prompt:


```
I need you to create a csv with the title of each song, the lyrics of each song, and a sentence describing the feelings of the song
```

### Aprimoração

O resultado das anotações iniciais todavia não era satisfatório, sentimentos genéricos e muitas vezes repetitivos foram atribuídos a músicas com sentimentos distintos.

As estratégias adotadas para aprimorar as anotações foram as seguintes:

1. Configurar a janela de contexto para 1.1M tokens
2. Aumentar o nível de raciocínio para "xhigh"
3. Descrever melhor o prompt, incluindo exemplos de sentimentos para músicas específicas. O prompt final utilizado foi o seguinte:

```
I need the feeling field to be more descriptive and individual to each song, for instance, Word on a Wing is a song that evokes a feeling of resignation to a higher power, a plea with God for direction, you can look the net for explanations too
```

## Pré-processamento

### Importando dados

In [55]:
import pandas as pd

lyrics = pd.read_csv("bowie_songs.csv")
lyrics

,title,lyrics,feelings
0,1917,(Instrumental),"Wordless and murky, this piece leans on its Fi..."
1,1984,"Someday they won't let you, now you must agree...","A funk-driven warning shot, it wraps claustrop..."
2,1984/Dodo,"Someday they won't let you, but now you must a...","Stitching dystopian alarm to hushed gossip, th..."
3,5:15 The Angels Have Gone,"5:15\nI'm changing trains, this little town\nL...","Set on a rainy platform, this is a farewell we..."
4,'87 And Cry,It's just a one dollar secret\nA lover's secre...,"Frustration curdles into bitterness, a snarlin..."
...,...,...,...
592,Word On A Wing,"In this age of grand delusion, you walked into...","Performed live, the hymn sounds even more expo..."
593,Yassassin,CHORUS\n Yassassin - I'm not a moody guy\n Y...,"A migrant's weary plea for peace, pride and ex..."
594,You Better Tell Her,NaN,"Impatient counsel drives the phrase, somebody ..."
595,You Can't Sit Down,Hey pretty baby! (you can't sit down)\nA don't...,"Irresistible compulsion to move, the beat trea..."
596,You Got To Have A Job (If You Don't Work - You...,They say you got to get a job\nTo put meat on ...,Funk-driven commentary on the grind of earning...

### Limpando dados

In [56]:
lyrics_clean = lyrics.dropna()
lyrics_clean

,title,lyrics,feelings
0,1917,(Instrumental),"Wordless and murky, this piece leans on its Fi..."
1,1984,"Someday they won't let you, now you must agree...","A funk-driven warning shot, it wraps claustrop..."
2,1984/Dodo,"Someday they won't let you, but now you must a...","Stitching dystopian alarm to hushed gossip, th..."
3,5:15 The Angels Have Gone,"5:15\nI'm changing trains, this little town\nL...","Set on a rainy platform, this is a farewell we..."
4,'87 And Cry,It's just a one dollar secret\nA lover's secre...,"Frustration curdles into bitterness, a snarlin..."
...,...,...,...
591,Without You I'm Nothing,Strange infatuation seems to grace the evening...,"Sultry self-abasement, decadent images sliding..."
592,Word On A Wing,"In this age of grand delusion, you walked into...","Performed live, the hymn sounds even more expo..."
593,Yassassin,CHORUS\n Yassassin - I'm not a moody guy\n Y...,"A migrant's weary plea for peace, pride and ex..."
595,You Can't Sit Down,Hey pretty baby! (you can't sit down)\nA don't...,"Irresistible compulsion to move, the beat trea..."
596,You Got To Have A Job (If You Don't Work - You...,They say you got to get a job\nTo put meat on ...,Funk-driven commentary on the grind of earning...

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

def most_similars(my_feeling_vec, vectors, top_n=5):
    similarities = cosine_similarity(my_feeling_vec, vectors)
    most_similar_indices = similarities.argsort()[0][-top_n:][::-1]
    return most_similar_indices

In [39]:
_test = [
    # Se errar esse tem alguma coisa errada
    ("I am on a disordered pilgrimage from occult dread toward desperate romance, a numbed figure pushing himself to feel anything at all.", "Station to Station"),
    # Esse pode ser acertado tanto pela letra quanto pelo sentimento
    ("I feel like I'm cracking under pressure and that only love can save me.", "Under Pressure"),
    # Relativamente fácil também, mas dá para errar
    ("I feel energized and want to dance with my beloved.", "Let's Dance"),
    ("I'm feeling regretful and ashemed for falling so low on my addiction.", "Ashes to Ashes"),
    ("I feel resignation, I just want to understand God's plan for me.", "Word on a Wing"),
    # Esse é o mais difícil, é necessário interpretar o contexto
    ("I'm completely head over heels in love and want to deliver myself completely", "I would be your slave"),
    # Bonus, não tem resposta certa, mas é interessante ver o que o modelo sugere
    ("I'm feeling anxious and stressed about an upcoming event.", "???"),
]

def as_rank(indices):
    return '\n'.join([
        f"\t\t{i + 1}. {lyrics_clean.iloc[indices[i]]['title']}"
        for i in range(5)
    ])

def test(feeling_vectorizer, feeling_vectors, lyrics_vectorizer, lyrics_vectors):
    for phrase, expected in _test:
        most_similar_by_feeling = most_similars(feeling_vectorizer(phrase), feeling_vectors, 5)
        most_similar_by_lyrics = most_similars(lyrics_vectorizer(phrase), lyrics_vectors, 5)
        print(f"Input phrase: {phrase}")
        print(f"\t* Expected: {expected}")
        print(f"\t* Most similar songs by feeling: \n{as_rank(most_similar_by_feeling)}")
        print(f"\t* Most similar songs by lyrics: \n{as_rank(most_similar_by_lyrics)}")
        print("\n")

## TF-IDF

A primeira abordagem, que servirá de base de comparação para as demais, é a utilização de TF-IDF (Term Frequency-Inverse Document Frequency) para transformar os sentimentos das músicas. Essa técnica permite identificar a importância de cada palavra em relação ao conjunto de documentos (neste caso, os sentimentos das músicas).

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

feelings_tfidf_vectorizer = TfidfVectorizer()
feelings_tfidf_matrix = feelings_tfidf_vectorizer.fit_transform(lyrics_clean['feelings'])

lyrics_tfidf_vectorizer = TfidfVectorizer()
lyrics_tfidf_matrix = lyrics_tfidf_vectorizer.fit_transform(lyrics_clean['lyrics'])

In [42]:
test(
    lambda x: feelings_tfidf_vectorizer.transform([x]),
    feelings_tfidf_matrix,
    lambda x: lyrics_tfidf_vectorizer.transform([x]),
    lyrics_tfidf_matrix
)

Input phrase: I am on a disordered pilgrimage from occult dread toward desperate romance, a numbed figure pushing himself to feel anything at all.
	* Expected: Station to Station
	* Most similar songs by feeling:
		1. Station To Station
		2. Goodbye Mr. Ed
		3. Soul Love
		4. Hurt
		5. After Today
	* Most similar songs by lyrics:
		1. I Am With Name
		2. The Pretty Things Are Going To Hell
		3. When The Wind Blows
		4. I Am A Laser
		5. Jewel


Input phrase: I feel energized and want to dance with my beloved.
	* Expected: Let's Dance
	* Most similar songs by feeling:
		1. Rupert The Riley
		2. Glad I've Got Nobody
		3. Let's Dance - (demo)
		4. Let's Dance
		5. Land Of 1,000 Dances
	* Most similar songs by lyrics:
		1. Let's Dance - (demo)
		2. Let's Dance
		3. Let's Dance
		4. I Feel So Bad
		5. Magic Dance


Input phrase: I'm feeling regretful for falling so low.
	* Expected: Ashes to Ashes
	* Most similar songs by feeling:
		1. I Can't Explain
		2. Things To Do
		3. The Secret Life Of Arabia
		4. It's So Easy
		5. Brussels
	* Most similar songs by lyrics:
		1. As The World Falls Down
		2. I've Been Waiting For You
		3. Holy Holy - (1971 version)
		4. I Can't Explain - (Trident Studios version)
		5. Holy Holy


Input phrase: I feel resignation, I just want to understand God's plan for me.
	* Expected: Word on a Wing
	* Most similar songs by feeling:
		1. Some Weird Sin
		2. I've Been Waiting For You
		3. Glad I've Got Nobody
		4. Starman - (demo 1 excerpt)
		5. What Kind Of Fool Am I?
	* Most similar songs by lyrics:
		1. Cygnet Committee
		2. God Knows I'm Good
		3. I Feel So Bad
		4. Under The God
		5. I Want My Baby Back - (demo)


Input phrase: I'm completely head over heels in love and want to deliver myself completely
	* Expected: I would be your slave
	* Most similar songs by feeling:
		1. I Dig Everything
		2. Blue Jean
		3. Glad I've Got Nobody
		4. Fill Your Heart
		5. Don't Let Me Down And Down
	* Most similar songs by lyrics:
		1. And I Say To Myself
		2. Absolute Beginners
		3. Cygnet Committee
		4. Soul Love
		5. Sweet Head


Input phrase: I'm feeling anxious and stressed about an upcoming event.
	* Expected: Unknown
	* Most similar songs by feeling:
		1. Speed Of Life
		2. I Pray, Olé
		3. Man In The Middle
		4. Modern Love
		5. Teenage Wildlife
	* Most similar songs by lyrics:
		1. I Took A Trip On A Gemini Spaceship
		2. I Can't Explain - (Trident Studios version)
		3. Come See About Me
		4. It's No Game (Part 2)
		5. Now

### Word2Vec

In [12]:
import gensim.downloader as api
import numpy as np
import nltk

nltk.download('punkt_tab')
# Load pre-trained Word2Vec model
word2vec_model = api.load("word2vec-google-news-300")
word2vec_model["love"]  # Example of getting the vector for a word

array([ 0.10302734, -0.15234375,  0.02587891,  0.16503906, -0.16503906,
        0.06689453,  0.29296875, -0.26367188, -0.140625  ,  0.20117188,
       -0.02624512, -0.08203125, -0.02770996, -0.04394531, -0.23535156,
        0.16992188,  0.12890625,  0.15722656,  0.00756836, -0.06982422,
       -0.03857422,  0.07958984,  0.22949219, -0.14355469,  0.16796875,
       -0.03515625,  0.05517578,  0.10693359,  0.11181641, -0.16308594,
       -0.11181641,  0.13964844,  0.01556396,  0.12792969,  0.15429688,
        0.07714844,  0.26171875,  0.08642578, -0.02514648,  0.33398438,
        0.18652344, -0.20996094,  0.07080078,  0.02600098, -0.10644531,
       -0.10253906,  0.12304688,  0.04711914,  0.02209473,  0.05834961,
       -0.10986328,  0.14941406, -0.10693359,  0.01556396,  0.08984375,
        0.11230469, -0.04370117, -0.11376953, -0.0037384 , -0.01818848,
        0.24316406,  0.08447266, -0.07080078,  0.18066406,  0.03515625,
       -0.09667969, -0.21972656, -0.00328064, -0.03198242,  0.18457031,
        0.28515625, -0.0859375 , -0.11181641,  0.0213623 , -0.30664062,
       -0.09228516, -0.18945312,  0.01513672,  0.18554688,  0.34375   ,
       -0.31054688,  0.22558594,  0.08740234, -0.2265625 , -0.29492188,
        0.08251953, -0.38476562,  0.25390625,  0.26953125,  0.06298828,
       -0.00958252,  0.23632812, -0.17871094, -0.12451172, -0.17285156,
       -0.11767578,  0.19726562, -0.03466797, -0.10400391, -0.1640625 ,
       -0.19726562,  0.19824219,  0.09521484,  0.00561523,  0.12597656,
        0.00073624, -0.0402832 , -0.03063965,  0.01623535, -0.1640625 ,
       -0.22167969,  0.171875  ,  0.12011719, -0.01965332,  0.4453125 ,
        0.06494141,  0.05932617, -0.1640625 , -0.01367188,  0.18945312,
        0.05566406, -0.05004883, -0.01422119,  0.15917969,  0.07421875,
       -0.31640625, -0.0534668 , -0.02355957, -0.16992188,  0.0625    ,
       -0.140625  , -0.13183594, -0.12792969,  0.12060547,  0.05883789,
       -0.00055695,  0.05761719, -0.08447266,  0.16992188,  0.13671875,
       -0.09375   ,  0.08056641, -0.04003906, -0.03759766, -0.26367188,
        0.00662231, -0.01928711,  0.09423828, -0.13183594, -0.27929688,
        0.27734375,  0.31835938,  0.10058594,  0.11425781, -0.27734375,
        0.11035156, -0.06982422, -0.0859375 , -0.11132812, -0.27929688,
       -0.07763672,  0.05102539, -0.06176758,  0.44921875,  0.01867676,
       -0.15039062,  0.13671875, -0.15039062, -0.2265625 ,  0.11914062,
        0.06005859, -0.0390625 , -0.10839844,  0.02905273,  0.02331543,
        0.13183594,  0.01000977,  0.03149414, -0.12597656, -0.13671875,
       -0.30664062, -0.28515625,  0.09863281, -0.00564575, -0.08398438,
       -0.16015625, -0.14453125, -0.18261719,  0.10009766,  0.04345703,
        0.10644531,  0.16503906,  0.06298828,  0.17578125,  0.15820312,
        0.125     ,  0.171875  , -0.05664062, -0.09033203, -0.21289062,
       -0.0390625 , -0.03320312, -0.18652344, -0.18945312, -0.01818848,
       -0.03051758, -0.17675781,  0.15234375,  0.01953125,  0.01696777,
       -0.10839844,  0.18066406,  0.00497437, -0.11621094, -0.19824219,
       -0.19140625,  0.21386719,  0.08984375, -0.16308594, -0.00325012,
       -0.07128906,  0.08251953,  0.02160645,  0.10107422, -0.29101562,
       -0.04785156, -0.03369141, -0.14453125, -0.06396484, -0.12451172,
       -0.24804688,  0.09277344,  0.01165771,  0.24707031,  0.3828125 ,
        0.02429199, -0.12255859,  0.00259399, -0.015625  ,  0.00540161,
        0.04736328, -0.00744629, -0.18261719,  0.21972656, -0.16601562,
        0.359375  ,  0.05297852, -0.03808594, -0.10400391, -0.18457031,
        0.07470703,  0.2734375 ,  0.28320312,  0.15234375,  0.05126953,
       -0.15429688, -0.15722656, -0.21582031, -0.19824219,  0.09960938,
       -0.09179688,  0.07519531, -0.02441406,  0.17382812, -0.11279297,
        0.00219727,  0.07470703, -0.02307129,  0.08642578,  0.16601562,
        0.07763672,  0.14746094,  0.15429688,  0.11425781,  0.14550781,
       -0.24023438, -0.2109375 ,  0.07421875, -0.14746094, -0.08642578,
        0.16113281, -0.07128906,  0.109375  ,  0.17675781,  0.18554688,
       -0.15820312, -0.2265625 ,  0.15039062, -0.08544922,  0.09130859,
       -0.03198242,  0.13476562, -0.15136719, -0.42773438, -0.03442383,
       -0.27929688,  0.125     , -0.19824219, -0.12304688,  0.06494141],
      dtype=float32)

In [15]:
from nltk.tokenize import word_tokenize
from gensim.models import KeyedVectors

def avg_w2v_vec(text, model: KeyedVectors):
    tokens = word_tokenize(text.lower())
    vectors = [
        model[t]
        for t in tokens
        if t in model
    ]

    if not vectors:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

[nltk_data] Downloading package punkt_tab to /home/fabio/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [16]:
feelings_word2vec_matrix = [
    avg_w2v_vec(feeling, word2vec_model)
    for feeling in lyrics_clean['feelings']
]

lyrics_word2vec_matrix = [
    avg_w2v_vec(lyric, word2vec_model)
    for lyric in lyrics_clean['lyrics']
]

In [43]:
def vectorize_with_word2vec(text):
    return avg_w2v_vec(text, word2vec_model).reshape(1, -1)

test(
    vectorize_with_word2vec,
    feelings_word2vec_matrix,
    vectorize_with_word2vec,
    lyrics_word2vec_matrix
)

Input phrase: I am on a disordered pilgrimage from occult dread toward desperate romance, a numbed figure pushing himself to feel anything at all.
	* Expected: Station to Station
	* Most similar songs by feeling:
		1. Station To Station
		2. I Took A Trip On A Gemini Spaceship
		3. When The Wind Blows
		4. Jump They Say
		5. Miracle Goodnight
	* Most similar songs by lyrics:
		1. The Supermen
		2. Baal's Hymn
		3. Ballad Of The Adventurers
		4. Soul Love
		5. Buddha Of Suburbia


Input phrase: I feel energized and want to dance with my beloved.
	* Expected: Let's Dance
	* Most similar songs by feeling:
		1. Fun
		2. Foot Stomping / I Wish I Could Shimmy Like My Sister Kate
		3. Knock On Wood
		4. Ragazzo Solo, Ragazza Sola
		5. Miracle Goodnight
	* Most similar songs by lyrics:
		1. John, I'm Only Dancing (Again)
		2. John, I'm Only Dancing
		3. Sweet Head
		4. Sweet Head - (Haddon Hall rehearsal)
		5. When I Live My Dream


Input phrase: I'm feeling regretful for falling so low.
	* Expected: Ashes to Ashes
	* Most similar songs by feeling:
		1. It's Gonna Be Me
		2. Hang Onto Yourself - (1971 version for Gene Vincent)
		3. Miracle Goodnight
		4. Fun
		5. Opening Titles Including Underground
	* Most similar songs by lyrics:
		1. I'm Not Losing Sleep
		2. Sorry
		3. Stateside
		4. Too Dizzy
		5. Some Weird Sin


Input phrase: I feel resignation, I just want to understand God's plan for me.
	* Expected: Word on a Wing
	* Most similar songs by feeling:
		1. Fun
		2. Knock On Wood
		3. Standing Next To You
		4. I've Been Waiting For You
		5. Kooks - (demo)
	* Most similar songs by lyrics:
		1. I Feel So Bad
		2. Afraid
		3. Things To Do
		4. Sorry
		5. And I Say To Myself


Input phrase: I'm completely head over heels in love and want to deliver myself completely
	* Expected: I would be your slave
	* Most similar songs by feeling:
		1. Absolute Beginners
		2. Fun
		3. Knock On Wood
		4. Survive
		5. Always Crashing In The Same Car
	* Most similar songs by lyrics:
		1. Mass Production
		2. Sweet Head - (Haddon Hall rehearsal)
		3. Tired Of My Life - (demo)
		4. Let's Spend The Night Together
		5. Janine


Input phrase: I'm feeling anxious and stressed about an upcoming event.
	* Expected: Unknown
	* Most similar songs by feeling:
		1. It's Gonna Be Me
		2. Perfect Day
		3. No Control
		4. Shapes Of Things
		5. Can You Hear Me
	* Most similar songs by lyrics:
		1. I'm Not Quite - (demo)
		2. Too Dizzy
		3. Letter To Hermione
		4. 1984
		5. Hoochie Coochie Man

In [21]:
def weighted_avg_w2v_vec(sentence, model, tfidf):
    words = word_tokenize(sentence.lower())
    vectors = []
    weights = []

    for word in words:
        if word in model and word in tfidf:
            vectors.append(model[word])
            weights.append(tfidf[word])

    if not vectors:
        return np.zeros(model.vector_size)

    return np.average(vectors, axis=0, weights=weights)

In [22]:
feeling_weighted_word2vec_matrix = [
    weighted_avg_w2v_vec(feeling, word2vec_model, feelings_tfidf_vectorizer.vocabulary_)
    for feeling in lyrics_clean['feelings']
]

lyrics_weighted_word2vec_matrix = [
    weighted_avg_w2v_vec(lyric, word2vec_model, lyrics_tfidf_vectorizer.vocabulary_)
    for lyric in lyrics_clean['lyrics']
]

In [41]:
def vectorize_with_weighted_word2vec(text):
    return weighted_avg_w2v_vec(text, word2vec_model, feelings_tfidf_vectorizer.vocabulary_).reshape(1, -1)

def vectorize_with_weighted_word2vec_lyrics(text):
    return weighted_avg_w2v_vec(text, word2vec_model, lyrics_tfidf_vectorizer.vocabulary_).reshape(1, -1)

test(
    vectorize_with_weighted_word2vec,
    feeling_weighted_word2vec_matrix,
    vectorize_with_weighted_word2vec_lyrics,
    lyrics_weighted_word2vec_matrix
)

Input phrase: I am on a disordered pilgrimage from occult dread toward desperate romance, a numbed figure pushing himself to feel anything at all.
	* Expected: Station to Station
	* Most similar songs by feeling:
		1. Station To Station
		2. Aladdin Sane (1913-1938-197?)
		3. The Width Of A Circle
		4. Tryin' To Get To Heaven
		5. China Girl
	* Most similar songs by lyrics:
		1. Soul Love
		2. God Knows I'm Good
		3. The Drowned Girl
		4. Life On Mars? - (demo)
		5. Soul Love - (demo)


Input phrase: I feel energized and want to dance with my beloved.
	* Expected: Let's Dance
	* Most similar songs by feeling:
		1. Standing Next To You
		2. Absolute Beginners
		3. Kooks - (demo)
		4. Can You Hear Me
		5. Fun
	* Most similar songs by lyrics:
		1. I Want My Baby Back - (demo)
		2. I Feel So Bad
		3. When I Live My Dream
		4. I Wanna Be Your Dog
		5. Cygnet Committee


Input phrase: I'm feeling regretful for falling so low.
	* Expected: Ashes to Ashes
	* Most similar songs by feeling:
		1. Things To Do
		2. Hang Onto Yourself - (1971 version for Gene Vincent)
		3. Miracle Goodnight
		4. Goodbye Mr. Ed
		5. Modern Love - ('Creation' version)
	* Most similar songs by lyrics:
		1. Cat People (Putting Out Fire)
		2. Station To Station
		3. It's So Easy
		4. As The World Falls Down
		5. Remembering Marie A.


Input phrase: I feel resignation, I just want to understand God's plan for me.
	* Expected: Word on a Wing
	* Most similar songs by feeling:
		1. I've Been Waiting For You
		2. What Kind Of Fool Am I?
		3. Standing Next To You
		4. Kooks - (demo)
		5. Can You Hear Me
	* Most similar songs by lyrics:
		1. I Can't Explain - (Trident Studios version)
		2. I Can't Explain
		3. I Feel So Bad
		4. Stay (Live 1976 bonus track)
		5. Yassassin


Input phrase: I'm completely head over heels in love and want to deliver myself completely
	* Expected: I would be your slave
	* Most similar songs by feeling:
		1. Absolute Beginners
		2. Standing Next To You
		3. Baby It Can't Fall
		4. God Only Knows
		5. Survive
	* Most similar songs by lyrics:
		1. I Feel So Bad
		2. Cygnet Committee
		3. Let's Spend The Night Together
		4. Under Pressure
		5. I Want My Baby Back - (demo)


Input phrase: I'm feeling anxious and stressed about an upcoming event.
	* Expected: Unknown
	* Most similar songs by feeling:
		1. Can You Hear Me
		2. It's Gonna Be Me
		3. Silly Boy Blue
		4. Tired Of My Life - (demo)
		5. Sorrow
	* Most similar songs by lyrics:
		1. Sweet Thing
		2. I Can't Explain - (Trident Studios version)
		3. I Feel So Bad
		4. I Can't Explain
		5. Rubber Band

## Doc2Vec

In [36]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

feelings_tags = [
    TaggedDocument(words=word_tokenize(feeling.lower()), tags=[str(i)])
    for i, feeling in enumerate(lyrics_clean['feelings'])
]

feelings_doc2vec = Doc2Vec(vector_size=100, window=5, min_count=1, workers=4, epochs=40)
feelings_doc2vec.build_vocab(feelings_tags)
feelings_doc2vec.train(feelings_tags, total_examples=feelings_doc2vec.corpus_count, epochs=feelings_doc2vec.epochs)

lyrics_tags = [
    TaggedDocument(words=word_tokenize(lyric.lower()), tags=[str(i)])
    for i, lyric in enumerate(lyrics_clean['lyrics'])
]

lyrics_doc2vec = Doc2Vec(vector_size=100, window=5, min_count=1, workers=4, epochs=40)
lyrics_doc2vec.build_vocab(lyrics_tags)
lyrics_doc2vec.train(lyrics_tags, total_examples=lyrics_doc2vec.corpus_count, epochs=lyrics_doc2vec.epochs)

In [40]:
def as_indices(rank):
    return [int(tag) for tag, _ in rank]

for phrase, expected in _test:
    most_similar_by_feeling = feelings_doc2vec.dv.most_similar(
        [feelings_doc2vec.infer_vector(word_tokenize(phrase.lower()))],
        topn=5
    )
    most_similar_by_lyrics = lyrics_doc2vec.dv.most_similar(
        [lyrics_doc2vec.infer_vector(word_tokenize(phrase.lower()))],
        topn=5
    )
    print(f"Input phrase: {phrase}")
    print(f"\t* Expected: {expected}")
    print(f"\t* Most similar songs by feeling: \n{as_rank(as_indices(most_similar_by_feeling))}")
    print(f"\t* Most similar songs by lyrics: \n{as_rank(as_indices(most_similar_by_lyrics))}")
    print("\n")

Input phrase: I am on a disordered pilgrimage from occult dread toward desperate romance, a numbed figure pushing himself to feel anything at all.
	* Expected: Station to Station
	* Most similar songs by feeling:
		1. Station To Station
		2. After Today
		3. Sector Z
		4. Saviour Machine
		5. Some Weird Sin
	* Most similar songs by lyrics:
		1. Golden Years (Instrumental)
		2. Nathan Adler - Segue 1
		3. Sense Of Doubt
		4. Lady Stardust - (Take 1 Alternative Version)
		5. Art Decade


Input phrase: I feel energized and want to dance with my beloved.
	* Expected: Let's Dance
	* Most similar songs by feeling:
		1. A Better Future
		2. The Passenger
		3. I Wanna Be Your Dog
		4. Bang Bang
		5. New Angels Of Promise
	* Most similar songs by lyrics:
		1. Land Of 1,000 Dances
		2. Soul Love - (demo)
		3. Baby Grace (A Horrid Cassette)
		4. Let's Dance - (demo)
		5. Stupidity


Input phrase: I'm feeling regretful for falling so low.
	* Expected: Ashes to Ashes
	* Most similar songs by feeling:
		1. Boys Keep Swinging
		2. Planet Of Dreams
		3. It's No Game (Part 1)
		4. All The Young Dudes
		5. Be My Wife
	* Most similar songs by lyrics:
		1. Blue Jean
		2. Harlem Shuffle
		3. Candidate - (working lyrics)
		4. Shakin' All Over
		5. O Superman


Input phrase: I feel resignation, I just want to understand God's plan for me.
	* Expected: Word on a Wing
	* Most similar songs by feeling:
		1. Some Weird Sin
		2. Friday On My Mind
		3. I'm Not Losing Sleep
		4. Joe The Lion
		5. Planet Of Dreams
	* Most similar songs by lyrics:
		1. No Control
		2. God Only Knows
		3. Space Oddity (re-recorded version)
		4. Heathen (The Rays)
		5. Right On Mother - (demo)


Input phrase: I'm completely head over heels in love and want to deliver myself completely
	* Expected: I would be your slave
	* Most similar songs by feeling:
		1. Real Cool World
		2. Cracked Actor
		3. Sorry
		4. When The Boys Come Marching Home
		5. Baby It Can't Fall
	* Most similar songs by lyrics:
		1. Run
		2. I Can't Explain - (Trident Studios version)
		3. I Wanna Be Your Dog
		4. I Can't Explain
		5. Moonage Daydream


Input phrase: I'm feeling anxious and stressed about an upcoming event.
	* Expected: Unknown
	* Most similar songs by feeling:
		1. Funtime
		2. Let Me Sleep Beside You - (2000 version)
		3. Now
		4. Brilliant Adventure
		5. Henry And The H-Bomb
	* Most similar songs by lyrics:
		1. South Horizon
		2. Golden Years (Instrumental)
		3. Abdulmajid
		4. 1917
		5. The Mysteries

## Transformers

In [44]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

/home/fabio/miniconda3/envs/maua/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1839.22it/s]

In [45]:
feelings_transformer_matrix = model.encode(lyrics_clean['feelings'].to_list())

lyrics_transformer_matrix = model.encode(lyrics_clean['lyrics'].to_list())

In [46]:

test(
    lambda x: model.encode([x]).reshape(1, -1),
    feelings_transformer_matrix,
    lambda x: model.encode([x]).reshape(1, -1),
    lyrics_transformer_matrix
)

Input phrase: I am on a disordered pilgrimage from occult dread toward desperate romance, a numbed figure pushing himself to feel anything at all.
	* Expected: Station to Station
	* Most similar songs by feeling:
		1. Station To Station
		2. Quicksand - (demo)
		3. The Width Of A Circle
		4. Turn Blue
		5. The Man Who Sold The World
	* Most similar songs by lyrics:
		1. The Voyeur Of Utter Destruction (As Beauty)
		2. Fill Your Heart
		3. Loving The Alien
		4. Like A Rolling Stone
		5. Quicksand - (demo)


Input phrase: I feel energized and want to dance with my beloved.
	* Expected: Let's Dance
	* Most similar songs by feeling:
		1. Let's Dance
		2. Land Of 1,000 Dances
		3. Harlem Shuffle
		4. As The World Falls Down
		5. Tiny Girls
	* Most similar songs by lyrics:
		1. I Feel Free
		2. Let's Dance - (demo)
		3. John, I'm Only Dancing
		4. Cosmic Dancer
		5. Dancing In The Street


Input phrase: I'm feeling regretful for falling so low.
	* Expected: Ashes to Ashes
	* Most similar songs by feeling:
		1. It's Gonna Be Me
		2. London Bye, Ta-Ta
		3. Quicksand
		4. Where Have All The Good Times Gone
		5. Red Money
	* Most similar songs by lyrics:
		1. Afraid
		2. I Feel So Bad
		3. Fantastic Voyage
		4. When The Wind Blows
		5. Like A Rolling Stone


Input phrase: I feel resignation, I just want to understand God's plan for me.
	* Expected: Word on a Wing
	* Most similar songs by feeling:
		1. Modern Love
		2. Quicksand
		3. Changes - (demo)
		4. Word On A Wing - (1976 Live bonus track)
		5. The Motel
	* Most similar songs by lyrics:
		1. Quicksand
		2. Quicksand - (demo)
		3. Word On A Wing - (1976 Live bonus track)
		4. Things To Do
		5. I Pray, Olé


Input phrase: I'm completely head over heels in love and want to deliver myself completely
	* Expected: I would be your slave
	* Most similar songs by feeling:
		1. Lady Grinning Soul
		2. Tiny Girls
		3. Station To Station
		4. Baby It Can't Fall
		5. China Girl
	* Most similar songs by lyrics:
		1. Jeepster
		2. I'm Deranged
		3. Absolute Beginners
		4. And I Say To Myself
		5. Lady Grinning Soul


Input phrase: I'm feeling anxious and stressed about an upcoming event.
	* Expected: Unknown
	* Most similar songs by feeling:
		1. Memory of a Free Festival
		2. Shapes Of Things
		3. Brilliant Adventure
		4. Five Years
		5. Time Will Crawl
	* Most similar songs by lyrics:
		1. Tired Of My Life - (demo)
		2. I Feel So Bad
		3. Baby Grace (A Horrid Cassette)
		4. When The Wind Blows
		5. It's No Game (Part 1)